drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
drop table if exists book cascade ;
create table book (book_genre tinyint not null check (book_genre between 0 and 3), book_version integer, book_creation_date timestamp(6), book_isbn bigint not null, book_update_date timestamp(6), book_id varchar(36) not null, book_name varchar(50) not null, primary key (book_id));
